# Generated by Django 4.0.5 on 2023-01-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property_detail',
            fields=[
                ('Pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('Property_name', models.CharField(max_length=100)),
                ('Property_address', models.CharField(max_length=200)),
                ('City_name', models.CharField(max_length=100)),
                ('State_name', models.CharField(max_length=100)),
            ],
        ),
    ]
